import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <div>
      <Head>
        <title>testing antd with rtl</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Testing AntD with RTL</h1>

        <ul>
          <li>
            <Link>
              <a href="/select">select</a>
            </Link>
          </li>
        </ul>
      </main>
    </div>
  );
}
